"""
Generates .sui definition files for ETS2/ATS paint jobs.

These .sui files typically store shared attributes for paint job accessories,
such as the name, price, unlock level, UI icon, and basic material properties.
They are included by the main .sii definition files.
"""
from pathlib import Path

def create_truck_sui(paint_id: str, path: Path, model: str) -> None:
    """
    Creates a .sui file with shared attributes for a truck paint job.

    The content includes common parameters like name (derived from paint_id),
    price, unlock level, UI icon reference, and material properties like
    airbrush behavior and base color.

    Args:
        paint_id (str): The unique identifier for the paint job (e.g., "skin001").
                        This is used for the 'name' and 'icon' fields.
        path (Path): The full path where the .sui file will be saved.
        model (str): The internal game model name of the truck (e.g., "scania.s_2016").
                     Currently unused in the SUI content itself but kept for consistency.
    """
    # The content is a simple text block defining paint job attributes.
    # These attributes are common for "Advanced truck skin (NextGen)" templates.
    content = f"""# Generated by ETS2/ATS Skin Pack Builder: Shared SUI for Truck

	name:					"{paint_id}"
	price:					1
	unlock:					0
	icon:					"{paint_id}"  # Refers to the UI icon (often derived from paint_id)
	airbrush:				true
	base_color_locked:		true
	base_color:				(0.600000, 0.600000, 0.600000)  # Default grey base color
	alternate_uvset:		false
"""

    # Write the generated content to the specified file path
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"    Successfully created truck SUI: {path}")
        
def create_trailer_sui(paint_id: str, path: Path, model: str) -> None:
    """
    Creates a .sui file with shared attributes for a trailer paint job.

    The content is identical to `create_truck_sui` in this implementation,
    providing common parameters like name, price, unlock level, UI icon,
    and basic material properties.

    Args:
        paint_id (str): The unique identifier for the paint job (e.g., "skin001").
                        This is used for the 'name' and 'icon' fields.
        path (Path): The full path where the .sui file will be saved.
        model (str): The internal game model name of the trailer (e.g., "scs_box").
                     Currently unused in the SUI content itself but kept for consistency.
    """
    # The content is a simple text block defining paint job attributes.
    # Note: This content is identical to the truck SUI in the current script version.
    content = f"""# Generated by ETS2/ATS Skin Pack Builder: Shared SUI for Trailer

	name:					"{paint_id}"
	price:					1
	unlock:					0
	icon:					"{paint_id}"  # Refers to the UI icon
	airbrush:				true
	base_color_locked:		true
	base_color:				(0.600000, 0.600000, 0.600000)  # Default grey base color
	alternate_uvset:		false
"""

    # Write the generated content to the specified file path
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"    Successfully created trailer SUI: {path}")